version: '3'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: nestauth
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: nestauth_db
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/data
